-- 球队表
CREATE TABLE `live_team`(
    `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(20) not NULL DEFAULT '',
    `image` VARCHAR(20) not NULL DEFAULT '',
    `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `creat_time` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `creat_time` int(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT charset=utf8;

-- 直播表
CREATE TABLE `live_game`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `a_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `b_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `a_score` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `b_score` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `narrator` VARCHAR(20) NOT NULL DEFAULT '',
    `image` VARCHAR(20) not NULL DEFAULT '',
	`start_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `creat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `creat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT charset=utf8;

-- 球员表
CREATE TABLE `live_player`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
    `image` VARCHAR(20) not NULL DEFAULT '',
	`age` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`positon` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `creat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `update_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT charset=utf8;

-- 赛事的赛况表
CREATE TABLE `live_outs`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `game_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`team_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`content` VARCHAR(200) NOT NULL DEFAULT '',
    `image` VARCHAR(20) not NULL DEFAULT '',
	`type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`creat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT charset=utf8;

-- 聊天室表
CREATE TABLE `live_chart`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `game_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`user_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`content` VARCHAR(200) NOT NULL DEFAULT '',
    `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`creat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT charset=utf8;